version: '3.5'
services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mygenesis
    hostname: mygenesis_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: mygenesis
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      mygenesis-network:
        aliases:
          - mygenesis_app_network
    tty: true
    ports:
      - "9000:9000"
    volumes:
       - ./:/var/www
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

# Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    depends_on:
      - app
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      mygenesis-network:
        aliases:
          - mygenesis_webserver_network

#Docker Networks
networks:
  mygenesis-network:
    name: mygenesis-network
    driver: bridge

volumes:
  dbdata:
    driver: local