version: 2.0

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9c:4a:e0:de:4a:39:6a:82:08:b0:31:76:dd:3a:8d:f1"
      - run: 
          name: Deploy My Genesis server
          command: |
            ssh -oStrictHostKeyChecking=no -v ${SSH_USER}@${SERVER_IP} "cd ${SERVER_SIDE_DIR} && git pull origin master && ./deploy.sh"
workflows:
  version: 2
  deployment:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
